variables: 
  location: westus
  groupId: logapp
  abbrevLocationName: westus
  instanceCount: 1
  identifier: sample-sb-conn
  sampleDirectory: tmi.logicapps
  sharedResourceGroupIdentifier: shared
parameters:
  - name: logicapp
    displayName: Select the logic app for deployment
    type: string
    default: ""
    values: 
      - "logic1"
      - "logic2"

trigger: none

stages:
- stage: Development
  jobs:
  - job: DeployDevelopmentEnvironment
    variables:
      environment: dev
    pool: 
      vmImage: 'windows-2019'
    steps:
    
    - script: |
       
       setlocal enabledelayedexpansion

        set "valueMap[logic1]=logic-app-definition1"
        set "valueMap[logic2]=logic-app-definition2"
        echo "value map set"
        echo ${{ parameters.logicapp }}
        set "selectedValue=${{ parameters.logicapp }}"
        echo Selected environment: %selectedValue%
        set "associatedValue=!valueMap[%selectedValue%]!"
        echo Associated value: %associatedValue%
        if "!associatedValue!"=="" (
          echo Error: Invalid 'logicapp' parameter value.
          exit /b 1
        )

        echo Selected environment: %selectedValue%
        echo Associated value: %associatedValue%
        echo ##vso[task.setvariable variable=logicAppName]%associatedValue%
        echo ##vso[task.setvariable variable=logicAppDefinitionPath]$(Build.Repository.LocalPath)\$(sampleDirectory)\templates\%associatedValue%.json
        echo ##vso[task.setvariable variable=logicAppDefinitionParametersFilePath]$(Build.Repository.LocalPath)\$(sampleDirectory)\templates\%associatedValue%-parameters.json
    - script: |
        echo ##vso[task.setvariable variable=resourceGroupName]$(groupId)$(environment)rgp$(location)-$(sharedResourceGroupIdentifier)
        echo ##vso[task.setvariable variable=templateFilePath]$(Build.Repository.LocalPath)\templates\shared-template.json
        echo ##vso[task.setvariable variable=logicAppDeployScript]$(Build.Repository.LocalPath)\powershell\logic-app-deploy.ps1
      name: setDynamicVariableNames
    - powershell: |
        Write-Host "definitionFilePath: $(logicAppDefinitionPath)"
        Write-Host "definitionParamFilePath: $(logicAppDefinitionParametersFilePath)"
        Write-Host "templateFilePath: $(templateFilePath)"
        Write-Host "resourceGroupName: $(resourceGroupName)"
        Write-Host "logicAppDeployScript: $(logicAppDeployScript)"
        Get-ChildItem -Path $(System.DefaultWorkingDirectory)
      name: printOutVariables
    - task: AzureResourceGroupDeployment@2
      name: SharedResourcesDeployment
      inputs:
        azureSubscription: 'Pay-As-You-Go (TMI Dev/Test) (855cfd52-2f2f-4a84-b698-8d8a995bd70f)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: Linked artifact
        csmFile: $(templateFilePath)
        deploymentMode: 'Incremental'
        deploymentName: $(Build.BuildNumber)
        overrideParameters: -groupId $(groupId) -environment $(environment) -locationName $(abbrevLocationName)
    - script: |
        echo ##vso[task.setvariable variable=connectorsTemplateFilePath]$(Build.Repository.LocalPath)\templates\connectors-template.json
        echo ##vso[task.setvariable variable=logicAppTemplateFilePath]$(Build.Repository.LocalPath)\templates\logic-app-template.json
      # echo ##vso[task.setvariable variable=logicAppDefinitionPath]$(Build.Repository.LocalPath)\$(sampleDirectory)\templates\logic-app-definition.json
      # echo ##vso[task.setvariable variable=logicAppDefinitionParametersFilePath]$(Build.Repository.LocalPath)\$(sampleDirectory)\templates\logic-app-definition-parameters.json
    - task: AzurePowerShell@4
      name: DeployLogicAppSample
      inputs:
        azureSubscription: 'Pay-As-You-Go (TMI Dev/Test) (855cfd52-2f2f-4a84-b698-8d8a995bd70f)'
        ScriptType: 'FilePath'
        ScriptPath: '$(logicAppDeployScript)'
        FailOnStandardError: true
        azurePowerShellVersion: LatestVersion
        ScriptArguments: >-
          -logicAppName $(logicAppName)
          -groupId $(groupId) 
          -location $(location) 
          -abbrevLocationName $(abbrevLocationName) 
          -environment $(environment) 
          -instanceCount $(instanceCount) 
          -identifier $(identifier) 
          -connectorsTemplateFilePath $(connectorsTemplateFilePath) 
          -logicAppTemplateFilePath $(logicAppTemplateFilePath) 
          -logicAppDefinitionPath $(logicAppDefinitionPath) 
          -logicAppDefinitionParametersFilePath $(logicAppDefinitionParametersFilePath)